# ----------------------------------------
name: My-GitHubActions-Basics
env: 
  APPLICATION_NAME: "MyPythonScript"
  PACKAGE_NAME    : "Python_deploy_ver-${{ github.sha }}"
  
on: 
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Massege in TEsting
      run : echo "Hello World from testing job"
    - name: Execute few commands
      run : |
        echo "Hello Message1"
        echo "Hello ApplicationName: ${{ env.APPLICATION_NAME }}"
  my_deploy:
    runs-on: ubuntu-latest
    needs  : [my_testing]
    
    steps:
    - name: Print Hello Massege in Deploy
      run : echo "Hello World from deploy job"
    - name: Execute several commands
      run : |
        echo "Deploy package 1"
        echo "Deploy package name ${{ env.PACKAGE_NAME }}"
    
