# ----------------------------------------
name: My-GitHubActions-Basics

on: 
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Massege in TEsting
      run: echo "Hello World from testing job"

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello Massege in Deploy
      run: echo "Hello World from deploy job"
    
    
