# ----------------------------------------
name: My-GitHubActions-Basics

on: 
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Massege
      run: echo "Hello World from testing job"

  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Massege
      run: echo "Hello World from deploy job"
    
    
